USE [master]
GO

/****** Object:  Database [Test_Master]    Script Date: 2017/7/14 星期五 10:04:37 ******/
CREATE DATABASE [Test_Master]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Test_Master', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Test_Master.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Test_Master_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Test_Master_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Test_Master] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Test_Master].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Test_Master] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Test_Master] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Test_Master] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Test_Master] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Test_Master] SET ARITHABORT OFF 
GO

ALTER DATABASE [Test_Master] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Test_Master] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Test_Master] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Test_Master] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Test_Master] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Test_Master] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Test_Master] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Test_Master] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Test_Master] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Test_Master] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Test_Master] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Test_Master] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Test_Master] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Test_Master] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Test_Master] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Test_Master] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Test_Master] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Test_Master] SET RECOVERY FULL 
GO

ALTER DATABASE [Test_Master] SET  MULTI_USER 
GO

ALTER DATABASE [Test_Master] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Test_Master] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Test_Master] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Test_Master] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Test_Master] SET  READ_WRITE 
GO


